In [3]:
import numpy as np

values = [0,10,15,20,25,30]
gamma = 0.9
alpha = 0.1
lamb = 0.3
z = np.zeros(6)
r = np.array([1,0,0,0,0,0])
w = values

index = -1
for _, val in enumerate(reversed(values)):
    gradient = np.zeros_like(z)
    gradient[index] = 1
    z = gamma*lamb*z + gradient
    delta = r[index-1] + gamma*values[index-1] - values[index]
    w += alpha*delta*z
    index -= 1
    print(w)


[ 0.   10.   15.   20.   25.   29.25]
[ 0.    10.    15.    20.    24.3   29.061]
[ 0.       10.       15.       19.35     24.1245   29.013615]
[ 0.        10.        14.4       19.188     24.08076   29.0018052]
[ 0.          9.1        14.157      19.12239    24.0630453  28.99702223]


IndexError: index -7 is out of bounds for axis 0 with size 6